name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'd10sport/front-academy-d10'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            # Navega al directorio del proyecto
            cd /var/www/html/d10/academy

            # Elimina todos los archivos, incluyendo ocultos
            rm -rf /var/www/html/d10/academy/* /var/www/html/d10/academy/.*

            # Clona el repositorio
            git clone https://github.com/d10sport/front-academy-d10.git .

            #Importar variables de entorno
            cp /var/www/html/params/d10/env_academy/.env /var/www/html/d10/academy

            # Verifica que el clon haya sido exitoso
            if [ ! -f package.json ]; then
              echo "Error: El clon del repositorio falló o no contiene package.json"
              exit 1
            fi

            # Instala las dependencias y construye el proyecto
            npm install
            npm run build
          EOF
